import logging
import re
from pathlib import Path
from typing import Any, Dict, Tuple, List

import ipdb

from cua.modules.util import save_image
from examples.setup import SetupController
from openhands.core.config import OpenHandsConfig
from openhands.events import EventStream
from openhands.events.action.os import OSWorldInteractiveAction
from openhands.runtime.impl.singularity.osworld_singularity_runtime import OSWorldSingularityRuntime
from openhands.storage import get_file_store
from openhands.core.logger import openhands_logger

# Create a child logger
logger = openhands_logger.getChild('env_controller')
logger.setLevel(logging.DEBUG)


class EnvController:
    """
    Static Wrapper class that interfaces with OSWorldSingularityRuntime.
    """
    @staticmethod
    async def initialize_runtime(job_id: str, vm_image_path: str, os_type: str,
                           osworld_setup: Dict) -> OSWorldSingularityRuntime:
        """
        Initialize OSWorldSingularityRuntime.
        Used by DataCollector._init_worker to boot up the VM.
        """
        config = OpenHandsConfig()
        config.runtime = "osworld"
        config.sandbox.base_container_image = "ubuntu:24.04"
        config.sandbox.run_as_fakeroot = False
        config.sandbox.runtime_container_image = None  # Trigger auto-build

        # Unique event stream per trajectory
        file_store = get_file_store('local', f'/tmp/synthetic_data_gen_{job_id}')
        event_stream = EventStream(sid=job_id, file_store=file_store)

        logger.debug(f"[initialize_runtime] Creating runtime for {job_id}")
        logger.debug(f"[initialize_runtime]   VM image: {vm_image_path}")
        logger.debug(f"[initialize_runtime]   Base image: {config.sandbox.base_container_image}")

        runtime = OSWorldSingularityRuntime(
            config=config,
            event_stream=event_stream,
            sid=job_id,
            os_type=os_type,
            vm_image_path=vm_image_path,
            attach_to_existing=False,
        )

        logger.debug(f"[initialize_runtime] Runtime object created, connecting to VM...")

        await runtime.connect()
        logger.debug(f"[initialize_runtime] ✓ Runtime initialized and connected for {job_id}")
        logger.debug(f"[initialize_runtime]   VM URL: {runtime.osworld_vm_url if hasattr(runtime, 'osworld_vm_url') else 'N/A'}")

        if osworld_setup and os_type == "linux":
            logger.debug(f"[initialize_runtime] Setting up OSWorld...")
            setup_controller = SetupController(
                vm_ip="127.0.0.1",
                server_port=runtime._vm_server_port,
                chromium_port=runtime._chromium_port,
                cache_dir="/tmp/osworld_example",  # might need to be changed to a unique directory for each job
                client_password="password",
                runtime=runtime
            )
            await setup_controller.setup(osworld_setup['config'])
            logger.debug(f"[initialize_runtime] ✓ OSWorld setup completed")
        else:
            logger.debug(f"[initialize_runtime] No OSWorld setup provided")

        return runtime

    @staticmethod
    def get_cursor_position(runtime: OSWorldSingularityRuntime) -> Tuple[int, int]:
        """
        Get cursor position from runtime
        """
        action = OSWorldInteractiveAction(
            method='execute_python_command',
            params={'command': 'import pyautogui; pos = pyautogui.position(); print(f"{pos.x},{pos.y}")'},
            thought='Getting cursor position'
        )
        cursor_obs = runtime.run_action(action)
        coords = cursor_obs.content.strip().split(",")
        return int(coords[0]), int(coords[1])

    @staticmethod
    def convert_action_dict(action_dict: Dict[str, Any], bbox_list: List) -> Dict[str, Any] | None:
        """
        Convert action_dict generated by OpenAIController into runtime-executable format.
        Returns None if action select is "done"
        """
        # if selected action is "done", we do not have to perform any action
        if action_dict["action"] in "done":
            return None

        # convert action_dict to match runtime syntax
        action_type, parameters = action_dict['action'], action_dict['parameters']
        converted_action_dict = {}

        action_type_dict = {
            "click": "CLICK",
            "double_click": "DOUBLE_CLICK",
            "right_click": "RIGHT_CLICK",
            "scroll": "SCROLL",
            "type": "TYPING",
            "hotkey": "HOTKEY",
            "wait": "WAIT",
        }
        converted_action_dict["action_type"] = action_type_dict[action_type]
        converted_action_dict["parameters"] = {}

        # infer x,y coordinates from object_idx
        if action_type in ["click", "double_click", "right_click", "scroll"]:
            if parameters["object_idx"] >= len(bbox_list):
                raise IndexError(f"object_idx {parameters['object_idx']} does not exist in the image.")
            [x1, y1, x2, y2] = bbox_list[parameters["object_idx"]]
            center_x, center_y = (x1 + x2) / 2, (y1 + y2) / 2

            converted_action_dict["parameters"]["x"] = center_x
            converted_action_dict["parameters"]["y"] = center_y

        if action_type == "scroll":
            converted_action_dict["parameters"]["amount"] = parameters["amount_to_scroll"]
        elif action_type == "type":
            converted_action_dict["parameters"]["text"] = parameters["type_list"]
        elif action_type == "hotkey":
            converted_action_dict["parameters"]["keys"] = parameters["type_list"]

        return converted_action_dict

    @staticmethod
    def execute_action(converted_action_dict: Dict[str, Any], runtime: OSWorldSingularityRuntime):
        """
        Execute the action given runtime and converted_action_dict.

        Args:
        converted_action_dict: Dict with "action_type" and "parameters"
        runtime: Runtime instance to execute action on

        Returns:
        Dictionary with `success`, `content`, `exit_code`
        """
        # reference: SyntheticDataGenerator.execute_action

        try:
            result = runtime.execute_vm_action(converted_action_dict)
            if result.get('status') == 'success':
                result =  {
                    'success': True,
                    'content': result.get('output', 'Action executed successfully'),
                    'exit_code': 0
                }
            else:
                error_msg = result.get('error', result.get('message', 'Unknown error'))
                result =  {
                    'success': False,
                    'content': error_msg,
                    'exit_code': -1
                }
            logger.debug(f"Action result: success={result['success']}")
            return result

        except Exception as e:
            logger.error(f"Error executing action: {e}")
            return {
                'success': False,
                'content': str(e),
                'exit_code': -1
            }

    @staticmethod
    def get_screen_size(runtime: OSWorldSingularityRuntime) -> Tuple[int, int]:
        observation = runtime.run_action(OSWorldInteractiveAction(
            method="get_vm_screen_size",
            params={},
            thought=""
        ))

        assert hasattr(observation, "content"), "get_screen_size failed."

        match = re.search(r"Width: (\d+), Height: (\d+)", observation.content)
        width, height = int(match.group(1)), int(match.group(2))

        return width, height

    @staticmethod
    def get_screenshot(runtime: OSWorldSingularityRuntime) -> bytes:
        """
        Returns the current screenshot from the runtime, in base64 format.
        If screenshot_path is set, save the screenshot as png.
        """
        screenshot = runtime.get_vm_screenshot()
        if not screenshot:
            logger.debug("✗ Failed to get screenshot from runtime.")
            raise RuntimeError("Failed to get screenshot from runtime.")

        return screenshot



